sudo: false

language: node_js

node_js:
  - 'stable'

install:
  - npm install

notifications:
  email: false

services:
  - postgresql

script:
  - npm run coverage

after_success:
  - npm run coveralls
